spring.config.import=optional:file:.env[.properties]

spring.application.name=project15years
spring.datasource.url=jdbc:postgresql://${DATABASE}/postgres?prepareThreshold=0
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.keepaliveTime=30000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
